version: "3"

services:
  api:
    build: ./server
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - "../MasterVAN/:/app"
    environment:
      - MONGO_DBNAME=prodmongo
      - MONGO_HOST=192.168.0.0

  postgres:
    image: postgres:9.6.2
    volumes:
    - ./postgres/data:/var/lib/postgresql/data
    ports:
    - "0.0.0.0:5432:5432"
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=root
  mongo:
    image: mongo:3.4
    volumes:
    - ./mongo/db:/data/db
    ports:
    - "0.0.0.0:27017:27017"
  mysql:
    image: mysql:5.7
    volumes:
    - /Users/ed/DB/mysql:/var/lib/mysql
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=TestDB
    - MYSQL_USER=VAN
    - MYSQL_PASSWORD=root
    ports:
    - "0.0.0.0:3306:3307"

  maria:
    image: mariadb
    restart: always
    command: --lower_case_table_names=1
    environment:
      MYSQL_ROOT_PASSWORD: 1qaz2wsx
    ports:
    - "0.0.0.0:3306:3306"